name: Test and Release

on:
    push:
        branches: [master]
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'
    pull_request: {}

permissions:
    contents: read

jobs:
    tests:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node-version: [22.x, 24.x]
                os: [ubuntu-latest, windows-latest, macos-latest]
        steps:
            - uses: actions/checkout@v6
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v7
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: npm

            - name: Install package
              run: npm ci

            - name: Validate package
              run: npm run check

    deploy:
        needs: [tests]

        if: startsWith(github.ref, 'refs/tags/v')
        runs-on: ubuntu-latest
        environment:
            name: npm
            url: https://www.npmjs.com/package/@micsob/bring-api-client
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v6
              with:
                  persist-credentials: false
            - name: Use Node.js
              uses: actions/setup-node@v7
              with:
                  node-version: 24
                  registry-url: 'https://registry.npmjs.org'
                  package-manager-cache: false

            - name: Install package
              run: npm ci

            - name: Publish package to npm
              run: npm publish --access public
